<?php
session_start();
// include_once('oauth.php');

// Pesapal parameters
$token = $params = null;

// PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your
// developement and  when you are ready to go live change to
// https://www.pesapal.com

// Register a merchant account on demo.pesapal.com and use the merchant key for
// testing. When you are ready to go live make sure you change the key to the
// live account registered on www.pesapal.com

 // $consumer_key = '6JdMvJRXbriqxfNmysvgcD0rGCjefFN3';
// $consumer_key = 'xN2px0DCDBvE9cIr+zEK2fH00/sRjTJW';
$consumer_key = '6JdMvJRXbriqxfNmysvgcD0rGCjefFN3';

// Use the secret from your test account on demo.pesapal.com. When you are ready
// to go live make sure you  change the secret to the live account registered on
// www.pesapal.com
 // $consumer_secret = 'jy3XgaKw9nK0Pwr2+nllq0/KTu4=';
// $consumer_secret = 'z3pein/v6RLsbAhyuC1zHffXahg=';
$consumer_secret = 'jy3XgaKw9nK0Pwr2+nllq0/KTu4=';

// Change this to https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you
// are ready to go live

//$iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4';
$iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';

// Get form details
// $amount         = (integer) $_POST['amount'];
// $desc           = $_POST['description'];
// $type           = $_POST['type'];                       // default value = MERCHANT
// $reference      = $_POST['reference'];                  // unique order id of the transaction, generated by merchant
// $first_name     = $_POST['first_name'];                 // optional
// $last_name      = $_POST['last_name'];                  // optional
// $email          = $_POST['email'];
// $phonenumber    = '';                                   // ONE of email or phonenumber is required


$currency       =$currency;
$amount         =$to_bepaid;
$desc           =$desc;
$type           =$type;                      // default value = MERCHANT
$tracking_id   = $reference_id;                  // unique order id of the transaction, generated by merchant

$transaction_id   = $reference_id; 

$reference_id  = uniqid("PAY_".$reference_id);
$first_name     =$first_name;                 // optional
$last_name      =$last_name;                 // optional
$email          =$email;
$phonenumber    =$phone;                                   // ONE of email or phonenumber is required

// $trackingID = (string) $tracking_id;
$value = Session::get('plan_id2');


//dd($gg);
//Session::put('transaction_id', 999);

// Define the callback_url i.e the redirect url, this page that will handle the
// response from pesapal.

//Updatating the transaction table

// $conn = mysqli_connect("localhost", "root", "", "dfarmdbb");
// $id = 1;
// $newRole = "Campaign Architect";

// $sql = "UPDATE transaction SET role='$newRole' WHERE id=$id";

// if (mysqli_query($conn, $sql)) {
//     echo "Record updated successfully";
// } else {
//     echo "Error updating record: " . mysqli_error($conn);
// }
// mysqli_close($conn);




// Callback URL (must be HTTPS in production)
$protocol   = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? "https://" : "http://";
$base_url   = $protocol . $_SERVER['HTTP_HOST'] . "/";
// $callback_url = $base_url . "callback.php";
dd($base_url);

$callback_url = $base_url . "pesapal/callback";


//$callback_url = "https://www.palatialholidays.com/pesapal/callback.php"; // must be HTTPS in production

$user_id=Auth::user()->id;
//dd($user_id);
// Connect to database
$conn = mysqli_connect("localhost", "root", "", "dfarmdbb");

// Check connection
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

//dd('print here2');

//Example: get data from users table
//$user_id = 1;
$result = mysqli_query($conn, "SELECT * FROM users WHERE id=$user_id");
$user = mysqli_fetch_assoc($result);

// $id = 1;
// $newRole = "Campaign Architect";
//dd($tracking_id);

$sql = "UPDATE transaction SET status='Paid',reference_id=$tracking_id,tracking_id=$tracking_id WHERE id=$transaction_id";

// Insert into another table
//dd($trackingID);

$action = "Updated role";
$sql = "INSERT INTO payments (customer_id,transaction_id,tracking_id,reference_id,amount_paid,currency,payee_date,status,created_at,updated_at) 
        VALUES ('$user_id',$transaction_id,$tracking_id,'$reference_id',$amount,'$currency',NOW(),'Paid', NOW(),NOW())";



if (mysqli_query($conn, $sql)) {
    echo "Data inserted into payments successfully";
} else {
    echo "Error: " . mysqli_error($conn);
}
mysqli_close($conn);



// The format is standard so no editing is required. Encode the variable using
// htmlentities.
$post_xml = '<?xml version="1.0" encoding="utf-8"?>';
$post_xml .= '<PesapalDirectOrderInfo ';
$post_xml .= 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ';
$post_xml .= 'xmlns:xsd="http://www.w3.org/2001/XMLSchema" ';
$post_xml .= 'Amount="'.$amount.'" ';
$post_xml .= 'Description="'.$desc.'" ';
$post_xml .= 'Type="'.$type.'" ';
$post_xml .= 'Reference="'.$reference_id.'" ';
$post_xml .= 'FirstName="'.$first_name.'" ';
$post_xml .= 'LastName="'.$last_name.'" ';
$post_xml .= 'Email="'.$email.'" ';
$post_xml .= 'PhoneNumber="'.$phonenumber.'" ';
$post_xml .= 'xmlns="http://www.pesapal.com" />';
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

// Construct the OAuth Request URL & post transaction to pesapal
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $iframelink, $params);
$iframe_src -> set_parameter('oauth_callback', $callback_url);
$iframe_src -> set_parameter('pesapal_request_data', $post_xml);
$iframe_src -> sign_request($signature_method, $consumer, $token);

// Display pesapal iframe and pass in iframe_src
?>
<iframe src="<?php echo $iframe_src; ?>" width="100%" height="800px"  scrolling="no" frameBorder="0">
    <p>Browser unable to load iFrame</p>
</iframe>
